"""Enterprise AI Identity, Access Intelligence, Authorization & Privileged Action Governance Platform (Phase 5.39)."""

from app.access_intelligence.exceptions import (
    AccessIntelligenceException,
    CrossTenantAccessIntelligenceException,
    IdentityNotFoundException,
    AccessRelationshipNotFoundException,
    EntitlementNotFoundException,
    PrivilegedAccessNotFoundException,
    AccessReviewNotFoundException,
    AccessCertificationNotFoundException,
    InvalidAccessStateTransitionException,
    AccessPolicyViolationException,
    PrivilegedActionBlockedException,
    AccessRiskThresholdExceededException,
    ImmutableAccessRecordException,
    AccessEvidenceIntegrityException,
    AccessDelegationBlockedException,
    HighRiskAccessRequiresApprovalException,
)
from app.access_intelligence.identities import (
    AccessIdentity,
    IdentityType,
    IdentityStatus,
    IdentityRiskLevel,
    IdentityReference,
    IdentityManager,
)
from app.access_intelligence.entitlements import (
    Entitlement,
    EntitlementType,
    EntitlementScope,
    EntitlementCriticality,
    EntitlementStatus,
    EntitlementReference,
    EntitlementManager,
)
from app.access_intelligence.relationships import (
    AccessRelationship,
    AccessRelationshipType,
    RelationshipStrength,
    RelationshipStatus,
    AccessRelationshipManager,
)
from app.access_intelligence.access_graph import (
    AccessGraph,
    AccessGraphNode,
    AccessGraphEdge,
    AccessGraphPath,
    AccessGraphTraversal,
    AccessGraphManager,
)
from app.access_intelligence.authorization import (
    AuthorizationRequest,
    AuthorizationDecision,
    AuthorizationDecisionOutcome,
    AuthorizationConstraint,
    AuthorizationEvidence,
    AuthorizationManager,
)
from app.access_intelligence.least_privilege import (
    LeastPrivilegeAssessment,
    PrivilegeGap,
    PrivilegeRecommendation,
    PrivilegeSeverity,
    LeastPrivilegeManager,
)
from app.access_intelligence.privileged_access import (
    PrivilegedAccessRequest,
    PrivilegedAccessScope,
    PrivilegedAccessStatus,
    PrivilegedAccessDuration,
    PrivilegedAccessManager,
)
from app.access_intelligence.emergency_access import (
    EmergencyAccessRequest,
    EmergencyAccessReason,
    EmergencyAccessStatus,
    EmergencyAccessVerification,
    EmergencyAccessManager,
)
from app.access_intelligence.access_risk import (
    AccessRiskProfile,
    AccessRiskDimension,
    AccessRiskAssessment,
    AccessRiskFactor,
    AccessRiskManager,
)
from app.access_intelligence.toxic_combinations import (
    ToxicCombination,
    ToxicCombinationRule,
    ToxicCombinationSeverity,
    ToxicCombinationEvidence,
    ToxicCombinationManager,
)
from app.access_intelligence.access_reviews import (
    AccessReview,
    AccessReviewScope,
    AccessReviewStatus,
    AccessReviewDecision,
    AccessReviewManager,
)
from app.access_intelligence.certifications import (
    AccessCertification,
    CertificationScope,
    CertificationStatus,
    CertificationDecision,
    AccessCertificationManager,
)
from app.access_intelligence.anomalies import (
    AccessAnomaly,
    AccessAnomalyType,
    AccessAnomalySeverity,
    AccessAnomalyConfidence,
    AccessAnomalyEvidence,
    AccessAnomalyManager,
)
from app.access_intelligence.signals import (
    AccessSignal,
    AccessSignalType,
    AccessSignalSeverity,
    AccessSignalSource,
    AccessSignalManager,
)
from app.access_intelligence.correlation import (
    AccessCorrelation,
    AccessCorrelationType,
    AccessCorrelationConfidence,
    AccessCorrelationEvidence,
    AccessCorrelationManager,
)
from app.access_intelligence.investigations import (
    AccessInvestigation,
    AccessInvestigationStatus,
    AccessFinding,
    AccessInvestigationManager,
)
from app.access_intelligence.remediation import (
    AccessRemediationPlan,
    AccessRemediationAction,
    AccessRemediationPriority,
    AccessRemediationStatus,
    AccessRemediationManager,
)
from app.access_intelligence.governance import (
    AccessGovernanceDecision,
    AccessGovernanceStatus,
    AccessGovernanceRequirement,
    AccessGovernanceEngine,
)
from app.access_intelligence.delegation import (
    AccessDelegationPlan,
    AccessDelegationAction,
    AccessDelegationStatus,
    AccessDelegationManager,
)
from app.access_intelligence.verification import (
    AccessVerification,
    VerificationCheck,
    VerificationStatus,
    AccessVerificationManager,
)
from app.access_intelligence.evidence import (
    AccessEvidence,
    AccessEvidenceBundle,
    AccessEvidenceIntegrity,
    AccessEvidenceManager,
)
from app.access_intelligence.snapshots import (
    AccessSnapshot,
    AccessSnapshotManager,
)
from app.access_intelligence.trust import (
    AccessTrustScore,
    AccessTrustDimension,
    AccessTrustFactor,
    AccessTrustEngine,
)
from app.access_intelligence.learning import (
    AccessLearningRecord,
    AccessPattern,
    AccessLearningRecommendation,
    AccessLearningManager,
)
from app.access_intelligence.analytics import (
    AccessAnalyticsEngine,
    AccessReport,
    AccessInsight,
)
from app.access_intelligence.observability import AccessMetricsCollector
from app.access_intelligence.billing import AccessCostEvent, AccessBillingTracker
from app.access_intelligence.repositories import TenantScopedRepository
from app.access_intelligence.manager import AccessIntelligenceManager

__all__ = [
    "AccessIntelligenceException",
    "CrossTenantAccessIntelligenceException",
    "IdentityNotFoundException",
    "AccessRelationshipNotFoundException",
    "EntitlementNotFoundException",
    "PrivilegedAccessNotFoundException",
    "AccessReviewNotFoundException",
    "AccessCertificationNotFoundException",
    "InvalidAccessStateTransitionException",
    "AccessPolicyViolationException",
    "PrivilegedActionBlockedException",
    "AccessRiskThresholdExceededException",
    "ImmutableAccessRecordException",
    "AccessEvidenceIntegrityException",
    "AccessDelegationBlockedException",
    "HighRiskAccessRequiresApprovalException",
    "AccessIdentity",
    "IdentityType",
    "IdentityStatus",
    "IdentityRiskLevel",
    "IdentityReference",
    "IdentityManager",
    "Entitlement",
    "EntitlementType",
    "EntitlementScope",
    "EntitlementCriticality",
    "EntitlementStatus",
    "EntitlementReference",
    "EntitlementManager",
    "AccessRelationship",
    "AccessRelationshipType",
    "RelationshipStrength",
    "RelationshipStatus",
    "AccessRelationshipManager",
    "AccessGraph",
    "AccessGraphNode",
    "AccessGraphEdge",
    "AccessGraphPath",
    "AccessGraphTraversal",
    "AccessGraphManager",
    "AuthorizationRequest",
    "AuthorizationDecision",
    "AuthorizationDecisionOutcome",
    "AuthorizationConstraint",
    "AuthorizationEvidence",
    "AuthorizationManager",
    "LeastPrivilegeAssessment",
    "PrivilegeGap",
    "PrivilegeRecommendation",
    "PrivilegeSeverity",
    "LeastPrivilegeManager",
    "PrivilegedAccessRequest",
    "PrivilegedAccessScope",
    "PrivilegedAccessStatus",
    "PrivilegedAccessDuration",
    "PrivilegedAccessManager",
    "EmergencyAccessRequest",
    "EmergencyAccessReason",
    "EmergencyAccessStatus",
    "EmergencyAccessVerification",
    "EmergencyAccessManager",
    "AccessRiskProfile",
    "AccessRiskDimension",
    "AccessRiskAssessment",
    "AccessRiskFactor",
    "AccessRiskManager",
    "ToxicCombination",
    "ToxicCombinationRule",
    "ToxicCombinationSeverity",
    "ToxicCombinationEvidence",
    "ToxicCombinationManager",
    "AccessReview",
    "AccessReviewScope",
    "AccessReviewStatus",
    "AccessReviewDecision",
    "AccessReviewManager",
    "AccessCertification",
    "CertificationScope",
    "CertificationStatus",
    "CertificationDecision",
    "AccessCertificationManager",
    "AccessAnomaly",
    "AccessAnomalyType",
    "AccessAnomalySeverity",
    "AccessAnomalyConfidence",
    "AccessAnomalyEvidence",
    "AccessAnomalyManager",
    "AccessSignal",
    "AccessSignalType",
    "AccessSignalSeverity",
    "AccessSignalSource",
    "AccessSignalManager",
    "AccessCorrelation",
    "AccessCorrelationType",
    "AccessCorrelationConfidence",
    "AccessCorrelationEvidence",
    "AccessCorrelationManager",
    "AccessInvestigation",
    "AccessInvestigationStatus",
    "AccessFinding",
    "AccessInvestigationManager",
    "AccessRemediationPlan",
    "AccessRemediationAction",
    "AccessRemediationPriority",
    "AccessRemediationStatus",
    "AccessRemediationManager",
    "AccessGovernanceDecision",
    "AccessGovernanceStatus",
    "AccessGovernanceRequirement",
    "AccessGovernanceEngine",
    "AccessDelegationPlan",
    "AccessDelegationAction",
    "AccessDelegationStatus",
    "AccessDelegationManager",
    "AccessVerification",
    "VerificationCheck",
    "VerificationStatus",
    "AccessVerificationManager",
    "AccessEvidence",
    "AccessEvidenceBundle",
    "AccessEvidenceIntegrity",
    "AccessEvidenceManager",
    "AccessSnapshot",
    "AccessSnapshotManager",
    "AccessTrustScore",
    "AccessTrustDimension",
    "AccessTrustFactor",
    "AccessTrustEngine",
    "AccessLearningRecord",
    "AccessPattern",
    "AccessLearningRecommendation",
    "AccessLearningManager",
    "AccessAnalyticsEngine",
    "AccessReport",
    "AccessInsight",
    "AccessMetricsCollector",
    "AccessCostEvent",
    "AccessBillingTracker",
    "TenantScopedRepository",
    "AccessIntelligenceManager",
]
