from enum import Enum


class PluginHook(str, Enum):
    STARTUP = "startup"
    SHUTDOWN = "shutdown"
    BEFORE_REQUEST = "before_request"
    AFTER_REQUEST = "after_request"
    BEFORE_INFERENCE = "before_inference"
    AFTER_INFERENCE = "after_inference"
    PROVIDER_SELECTED = "provider_selected"
    PROVIDER_FAILED = "provider_failed"
    PLUGIN_LOADED = "plugin_loaded"
    PLUGIN_UNLOADED = "plugin_unloaded"
    SYSTEM_STARTUP = "system.startup"
    SYSTEM_SHUTDOWN = "system.shutdown"
    BEFORE_INDEX = "before_index"
    AFTER_INDEX = "after_index"
    BEFORE_SEARCH = "before_search"
    AFTER_SEARCH = "after_search"
    BEFORE_EMBEDDING = "before_embedding"
    AFTER_EMBEDDING = "after_embedding"
    BEFORE_MEMORY_STORE = "before_memory_store"
    AFTER_MEMORY_STORE = "after_memory_store"
    BEFORE_MEMORY_RETRIEVE = "before_memory_retrieve"
    AFTER_MEMORY_RETRIEVE = "after_memory_retrieve"
    BEFORE_MEMORY_COMPRESS = "before_memory_compress"
    AFTER_MEMORY_COMPRESS = "after_memory_compress"
    BEFORE_MEMORY_ARCHIVE = "before_memory_archive"
    AFTER_MEMORY_ARCHIVE = "after_memory_archive"
    BEFORE_MEMORY_EXPIRE = "before_memory_expire"
    AFTER_MEMORY_EXPIRE = "after_memory_expire"
