"""Policy Simulator analyzing dry-run impact before policy activation."""

import logging
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.control_plane.policy_manager import PolicyManager, PolicyTargetType
from app.control_plane.resource_registry import ResourceRegistry

logger = logging.getLogger(__name__)


class PolicyImpactReport(BaseModel):
    """Impact evaluation report generated by policy dry-run simulation."""

    policy_name: str
    target_type: PolicyTargetType
    total_resources_evaluated: int
    blocked_resources_count: int
    blocked_resource_ids: List[str] = Field(default_factory=list)
    conflicting_policy_ids: List[str] = Field(default_factory=list)
    estimated_affected_executions: int = 0
    recommendation: str = "PROCEED"  # 'PROCEED', 'WARNING', 'REJECT'


class PolicySimulator:
    """Simulates prospective policy rules against active platform resources."""

    def __init__(
        self, policy_manager: Optional[PolicyManager] = None, resource_registry: Optional[ResourceRegistry] = None
    ) -> None:
        self.policy_manager = policy_manager or PolicyManager()
        self.resource_registry = resource_registry or ResourceRegistry()

    def simulate_policy_impact(
        self,
        name: str,
        target_type: PolicyTargetType,
        rules: Dict[str, Any],
        tenant_id: str = "global",
    ) -> PolicyImpactReport:
        """Dry-run policy evaluation across registered inventory."""
        # 1. Fetch matching inventory resources
        resources = self.resource_registry.list_resources(tenant_id=tenant_id)
        blocked_ids: List[str] = []
        deny_actions = rules.get("deny_actions", [])

        for res in resources:
            # Simple simulation heuristic against resource metadata
            if deny_actions and "*" in deny_actions:
                blocked_ids.append(res.resource_id)

        # 2. Check for conflicting policies
        existing = self.policy_manager.list_policies(tenant_id=tenant_id, target_type=target_type)
        conflicts = [p.policy_id for p in existing if p.is_active and p.rules.get("deny_actions") == deny_actions]

        rec = "PROCEED"
        if len(blocked_ids) > 10 or conflicts:
            rec = "WARNING"

        logger.info(
            f"[POLICY SIMULATOR] Simulated policy '{name}': {len(blocked_ids)} blocked resources, {len(conflicts)} conflicts"
        )
        return PolicyImpactReport(
            policy_name=name,
            target_type=target_type,
            total_resources_evaluated=len(resources),
            blocked_resources_count=len(blocked_ids),
            blocked_resource_ids=blocked_ids,
            conflicting_policy_ids=conflicts,
            estimated_affected_executions=len(blocked_ids) * 5,
            recommendation=rec,
        )
