"""Centralized Platform Resource Inventory & Registry."""

import logging
from enum import Enum
from typing import Dict, Any, Optional, List
from datetime import datetime, timezone
import uuid
from pydantic import BaseModel, Field

from app.control_plane.exceptions import ResourceNotFoundException

logger = logging.getLogger(__name__)


class ResourceType(str, Enum):
    MODEL = "MODEL"
    PROVIDER = "PROVIDER"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    DOCUMENT = "DOCUMENT"
    AGENT = "AGENT"
    AGENT_TEAM = "AGENT_TEAM"
    WORKFLOW = "WORKFLOW"
    TOOL = "TOOL"
    MCP_SERVER = "MCP_SERVER"
    MEMORY = "MEMORY"
    PLAN = "PLAN"
    AUTONOMOUS_EXECUTION = "AUTONOMOUS_EXECUTION"
    DIGITAL_WORKER = "DIGITAL_WORKER"
    API_KEY = "API_KEY"
    SECRET_REFERENCE = "SECRET_REFERENCE"
    FEATURE_FLAG = "FEATURE_FLAG"
    DEVELOPER = "DEVELOPER"
    DEVELOPER_PROJECT = "DEVELOPER_PROJECT"
    EXTENSION = "EXTENSION"
    EXTENSION_VERSION = "EXTENSION_VERSION"
    MARKETPLACE_ITEM = "MARKETPLACE_ITEM"
    MARKETPLACE_INSTALLATION = "MARKETPLACE_INSTALLATION"
    MCP_PACKAGE = "MCP_PACKAGE"
    WEBHOOK_SUBSCRIPTION = "WEBHOOK_SUBSCRIPTION"
    DATA_SOURCE = "DATA_SOURCE"
    DATA_CONNECTOR = "DATA_CONNECTOR"
    DATASET = "DATASET"
    DATA_ASSET = "DATA_ASSET"
    DATA_SCHEMA = "DATA_SCHEMA"
    DATA_SYNC = "DATA_SYNC"
    DATA_LINEAGE = "DATA_LINEAGE"
    DATA_POLICY = "DATA_POLICY"
    AI_ASSET = "AI_ASSET"
    AI_ASSET_VERSION = "AI_ASSET_VERSION"
    MODEL_VERSION = "MODEL_VERSION"
    PROMPT = "PROMPT"
    PROMPT_VERSION = "PROMPT_VERSION"
    EXPERIMENT = "EXPERIMENT"
    EVALUATION_DATASET = "EVALUATION_DATASET"
    EVALUATION_RUN = "EVALUATION_RUN"
    DEPLOYMENT = "DEPLOYMENT"
    RELEASE = "RELEASE"
    RELEASE_ARTIFACT = "RELEASE_ARTIFACT"
    ROLLBACK = "ROLLBACK"
    DRIFT_EVENT = "DRIFT_EVENT"
    COST_LEDGER = "COST_LEDGER"
    BUDGET = "BUDGET"
    COST_FORECAST = "COST_FORECAST"
    COST_ANOMALY = "COST_ANOMALY"
    OPTIMIZATION_RECOMMENDATION = "OPTIMIZATION_RECOMMENDATION"
    OPTIMIZATION_EXECUTION = "OPTIMIZATION_EXECUTION"
    SAVINGS_RECORD = "SAVINGS_RECORD"
    CAPACITY_PLAN = "CAPACITY_PLAN"
    PRICING_CATALOG = "PRICING_CATALOG"
    CHARGEBACK_REPORT = "CHARGEBACK_REPORT"
    TELEMETRY_STREAM = "TELEMETRY_STREAM"
    SERVICE_TOPOLOGY = "SERVICE_TOPOLOGY"
    SERVICE_LEVEL_OBJECTIVE = "SERVICE_LEVEL_OBJECTIVE"
    ERROR_BUDGET = "ERROR_BUDGET"
    ALERT_RULE = "ALERT_RULE"
    ALERT = "ALERT"
    INCIDENT = "INCIDENT"
    ROOT_CAUSE_ANALYSIS = "ROOT_CAUSE_ANALYSIS"
    RUNBOOK = "RUNBOOK"
    RUNBOOK_EXECUTION = "RUNBOOK_EXECUTION"
    REMEDIATION_PLAN = "REMEDIATION_PLAN"
    REMEDIATION_EXECUTION = "REMEDIATION_EXECUTION"
    FAILURE_PREDICTION = "FAILURE_PREDICTION"
    POSTMORTEM = "POSTMORTEM"
    GOVERNANCE_FRAMEWORK = "GOVERNANCE_FRAMEWORK"
    GOVERNANCE_CONTROL = "GOVERNANCE_CONTROL"
    RISK = "RISK"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    COMPLIANCE_FRAMEWORK = "COMPLIANCE_FRAMEWORK"
    COMPLIANCE_REQUIREMENT = "COMPLIANCE_REQUIREMENT"
    COMPLIANCE_ASSESSMENT = "COMPLIANCE_ASSESSMENT"
    COMPLIANCE_FINDING = "COMPLIANCE_FINDING"
    GOVERNANCE_EVIDENCE = "GOVERNANCE_EVIDENCE"
    GOVERNANCE_DECISION = "GOVERNANCE_DECISION"
    GOVERNANCE_VIOLATION = "GOVERNANCE_VIOLATION"
    TRUST_ASSESSMENT = "TRUST_ASSESSMENT"
    AUTONOMY_POLICY = "AUTONOMY_POLICY"
    GOVERNANCE_REMEDIATION = "GOVERNANCE_REMEDIATION"
    IDENTITY = "IDENTITY"
    ROLE = "ROLE"
    PERMISSION = "PERMISSION"
    ACCESS_POLICY = "ACCESS_POLICY"
    AUTH_SESSION = "AUTH_SESSION"
    CREDENTIAL = "CREDENTIAL"
    PRIVILEGED_ACCESS = "PRIVILEGED_ACCESS"
    WORKLOAD_IDENTITY = "WORKLOAD_IDENTITY"
    IDENTITY_RISK_EVENT = "IDENTITY_RISK_EVENT"
    ACCESS_REVIEW = "ACCESS_REVIEW"
    DELEGATED_AUTHORIZATION = "DELEGATED_AUTHORIZATION"
    ZERO_TRUST_POLICY = "ZERO_TRUST_POLICY"
    WORKFLOW_DEFINITION = "WORKFLOW_DEFINITION"
    WORKFLOW_VERSION = "WORKFLOW_VERSION"
    # Phase 5.18 Resource Types
    ORCHESTRATION_WORKFLOW = "ORCHESTRATION_WORKFLOW"
    ORCHESTRATION_EXECUTION = "ORCHESTRATION_EXECUTION"
    HUMAN_TASK = "HUMAN_TASK"
    ENTERPRISE_CASE = "ENTERPRISE_CASE"
    EXECUTION_ROUTE = "EXECUTION_ROUTE"
    AGENT_ORCHESTRATION = "AGENT_ORCHESTRATION"
    DECISION_TABLE = "DECISION_TABLE"
    ORCHESTRATION_EVENT = "ORCHESTRATION_EVENT"
    SAGA_TRANSACTION = "SAGA_TRANSACTION"
    WORKFLOW_GOVERNANCE = "WORKFLOW_GOVERNANCE"
    PROCESS_ANALYTICS = "PROCESS_ANALYTICS"
    ORCHESTRATION_METRICS = "ORCHESTRATION_METRICS"

    # Phase 5.19 Resource Types
    KNOWLEDGE_ITEM = "KNOWLEDGE_ITEM"
    KNOWLEDGE_VERSION = "KNOWLEDGE_VERSION"
    KNOWLEDGE_SOURCE = "KNOWLEDGE_SOURCE"
    KNOWLEDGE_GRAPH = "KNOWLEDGE_GRAPH"
    KNOWLEDGE_NODE = "KNOWLEDGE_NODE"
    KNOWLEDGE_EDGE = "KNOWLEDGE_EDGE"
    CONTEXT = "CONTEXT"
    CONTEXT_POLICY = "CONTEXT_POLICY"
    KNOWLEDGE_CONFLICT = "KNOWLEDGE_CONFLICT"
    PROVENANCE_RECORD = "PROVENANCE_RECORD"

    # Phase 5.20 Resource Types
    INTEGRATION = "INTEGRATION"
    INTEGRATION_CONNECTOR = "INTEGRATION_CONNECTOR"
    INTEGRATION_CREDENTIAL = "INTEGRATION_CREDENTIAL"
    WEBHOOK = "WEBHOOK"
    EVENT_SUBSCRIPTION = "EVENT_SUBSCRIPTION"
    AUTOMATION = "AUTOMATION"
    PLUGIN = "PLUGIN"
    PLUGIN_VERSION = "PLUGIN_VERSION"
    MARKETPLACE_LISTING = "MARKETPLACE_LISTING"
    INTEGRATION_EXECUTION = "INTEGRATION_EXECUTION"

    # Phase 5.21 Resource Types
    REPOSITORY = "REPOSITORY"
    API_PRODUCT = "API_PRODUCT"
    API_CONTRACT = "API_CONTRACT"
    API_VERSION = "API_VERSION"
    DEVELOPER_APPLICATION = "DEVELOPER_APPLICATION"
    SDK_ARTIFACT = "SDK_ARTIFACT"
    DEVELOPER_WORKSPACE = "DEVELOPER_WORKSPACE"
    PIPELINE = "PIPELINE"
    PIPELINE_RUN = "PIPELINE_RUN"
    QUALITY_GATE = "QUALITY_GATE"
    SOFTWARE_RELEASE = "SOFTWARE_RELEASE"
    DEPENDENCY_RISK = "DEPENDENCY_RISK"
    DEVELOPER_INSIGHT = "DEVELOPER_INSIGHT"

    # Phase 5.22 Resource Types
    APPLICATION = "APPLICATION"
    APPLICATION_VERSION = "APPLICATION_VERSION"
    APPLICATION_CONFIGURATION = "APPLICATION_CONFIGURATION"
    APPLICATION_EXECUTION = "APPLICATION_EXECUTION"
    APPLICATION_COMPOSITION = "APPLICATION_COMPOSITION"
    APPLICATION_DEPLOYMENT = "APPLICATION_DEPLOYMENT"
    FEATURE_EXPERIMENT = "FEATURE_EXPERIMENT"
    APPLICATION_INTERACTION = "APPLICATION_INTERACTION"
    APPLICATION_REPORT = "APPLICATION_REPORT"
    # Phase 5.23 Resource Types
    SERVICE = "SERVICE"
    SERVICE_DEPENDENCY = "SERVICE_DEPENDENCY"
    SERVICE_SLO = "SERVICE_SLO"
    OPERATIONAL_SIGNAL = "OPERATIONAL_SIGNAL"
    ANOMALY = "ANOMALY"
    CAPACITY_ASSESSMENT = "CAPACITY_ASSESSMENT"
    OPERATIONAL_INSIGHT = "OPERATIONAL_INSIGHT"
    # Phase 5.24 Resource Types
    INTEGRATION_SIGNAL = "INTELLIGENCE_SIGNAL"
    INTELLIGENCE_CONTEXT = "INTELLIGENCE_CONTEXT"
    INSIGHT = "INSIGHT"
    FORECAST = "FORECAST"
    SIMULATION = "SIMULATION"
    DECISION = "DECISION"
    RECOMMENDATION = "RECOMMENDATION"
    DECISION_OUTCOME = "DECISION_OUTCOME"
    OPTIMIZATION = "OPTIMIZATION"

    # Phase 5.25 Resource Types
    DATA_CONTRACT = "DATA_CONTRACT"
    DATA_QUALITY_RESULT = "DATA_QUALITY_RESULT"
    DATA_CONSENT = "DATA_CONSENT"
    DATA_ACCESS_REQUEST = "DATA_ACCESS_REQUEST"
    DATA_SHARE = "DATA_SHARE"
    RETENTION_POLICY = "RETENTION_POLICY"
    DATA_TRUST_SCORE = "DATA_TRUST_SCORE"
    DATA_GOVERNANCE_REPORT = "DATA_GOVERNANCE_REPORT"

    # Phase 5.26 Resource Types
    ARCHITECTURE_NODE = "ARCHITECTURE_NODE"
    ARCHITECTURE_DEPENDENCY = "ARCHITECTURE_DEPENDENCY"
    ARCHITECTURE_TOPOLOGY = "ARCHITECTURE_TOPOLOGY"
    ARCHITECTURE_SNAPSHOT = "ARCHITECTURE_SNAPSHOT"
    ARCHITECTURE_CHANGE = "ARCHITECTURE_CHANGE"
    ARCHITECTURE_DECISION = "ARCHITECTURE_DECISION"
    ARCHITECTURE_DRIFT = "ARCHITECTURE_DRIFT"
    ARCHITECTURE_IMPACT = "ARCHITECTURE_IMPACT"
    ARCHITECTURE_TRUST_SCORE = "ARCHITECTURE_TRUST_SCORE"

    # Phase 5.27 Resource Types
    COMPLIANCE_CONTROL = "COMPLIANCE_CONTROL"
    COMPLIANCE_EVIDENCE = "COMPLIANCE_EVIDENCE"
    COMPLIANCE_EVIDENCE_BUNDLE = "COMPLIANCE_EVIDENCE_BUNDLE"
    COMPLIANCE_REMEDIATION = "COMPLIANCE_REMEDIATION"
    COMPLIANCE_ATTESTATION = "COMPLIANCE_ATTESTATION"
    COMPLIANCE_EXCEPTION = "COMPLIANCE_EXCEPTION"
    COMPLIANCE_POSTURE = "COMPLIANCE_POSTURE"
    COMPLIANCE_ASSURANCE_REPORT = "COMPLIANCE_ASSURANCE_REPORT"
    # Phase 5.28 Resource Types
    ENTERPRISE_STRATEGY = "ENTERPRISE_STRATEGY"
    BUSINESS_OBJECTIVE = "BUSINESS_OBJECTIVE"
    AI_OPPORTUNITY = "AI_OPPORTUNITY"
    AI_INITIATIVE = "AI_INITIATIVE"
    BUSINESS_CASE = "BUSINESS_CASE"
    INVESTMENT = "INVESTMENT"
    FUNDING_REQUEST = "FUNDING_REQUEST"
    PORTFOLIO = "PORTFOLIO"
    PORTFOLIO_SNAPSHOT = "PORTFOLIO_SNAPSHOT"
    VALUE_MEASUREMENT = "VALUE_MEASUREMENT"
    BENEFIT = "BENEFIT"
    PORTFOLIO_RECOMMENDATION = "PORTFOLIO_RECOMMENDATION"
    # Phase 5.29 Resource Types
    ENTERPRISE_DECISION = "ENTERPRISE_DECISION"
    DECISION_CONTEXT = "DECISION_CONTEXT"
    DECISION_EVIDENCE = "DECISION_EVIDENCE"
    DECISION_SCENARIO = "DECISION_SCENARIO"
    DECISION_RECOMMENDATION = "DECISION_RECOMMENDATION"
    DECISION_TRUST_SCORE = "DECISION_TRUST_SCORE"
    DECISION_DELEGATION = "DECISION_DELEGATION"
    # Phase 5.30 Generic Shared Contract Resource Types
    PLATFORM_SNAPSHOT = "PLATFORM_SNAPSHOT"
    DELEGATION_REQUEST = "DELEGATION_REQUEST"
    EVIDENCE_REFERENCE = "EVIDENCE_REFERENCE"
    # Phase 5.31 Reliability Platform Resource Types
    RELIABILITY_SERVICE = "RELIABILITY_SERVICE"
    SLO_DEFINITION = "SLO_DEFINITION"
    RELIABILITY_INCIDENT = "RELIABILITY_INCIDENT"
    POSTMORTEM_REPORT = "POSTMORTEM_REPORT"
    # Phase 5.32 Security Intelligence Resource Types
    SECURITY_ASSET = "SECURITY_ASSET"
    SECURITY_SIGNAL = "SECURITY_SIGNAL"
    SECURITY_THREAT = "SECURITY_THREAT"
    AI_SECURITY_THREAT = "AI_SECURITY_THREAT"
    SECURITY_VULNERABILITY = "SECURITY_VULNERABILITY"
    SECURITY_ATTACK_PATH = "SECURITY_ATTACK_PATH"
    SECURITY_INCIDENT = "SECURITY_INCIDENT"
    SECURITY_INVESTIGATION = "SECURITY_INVESTIGATION"
    SECURITY_REMEDIATION = "SECURITY_REMEDIATION"
    SECURITY_POSTURE = "SECURITY_POSTURE"
    SECURITY_EVIDENCE = "SECURITY_EVIDENCE"
    SECURITY_TRUST_SCORE = "SECURITY_TRUST_SCORE"
    # Phase 5.33 AI Lifecycle Platform Resource Types
    AI_LIFECYCLE_ASSET = "AI_LIFECYCLE_ASSET"
    AI_DATASET_VERSION = "AI_DATASET_VERSION"
    AI_MODEL_VERSION = "AI_MODEL_VERSION"
    AI_AGENT_VERSION = "AI_AGENT_VERSION"
    AI_EVALUATION = "AI_EVALUATION"
    AI_LIFECYCLE_GATE = "AI_LIFECYCLE_GATE"
    AI_PROMOTION = "AI_PROMOTION"
    AI_RELEASE = "AI_RELEASE"
    AI_DRIFT_EVENT = "AI_DRIFT_EVENT"
    AI_ROLLBACK = "AI_ROLLBACK"
    AI_RETIREMENT = "AI_RETIREMENT"
    AI_LIFECYCLE_SNAPSHOT = "AI_LIFECYCLE_SNAPSHOT"
    # Phase 5.34 Event Intelligence Resource Types
    ENTERPRISE_EVENT = "ENTERPRISE_EVENT"
    EVENT_SOURCE = "EVENT_SOURCE"
    EVENT_CORRELATION = "EVENT_CORRELATION"
    EVENT_AUTOMATION_RULE = "EVENT_AUTOMATION_RULE"
    EVENT_AUTOMATION_PLAN = "EVENT_AUTOMATION_PLAN"
    EVENT_INVESTIGATION = "EVENT_INVESTIGATION"
    EVENT_RESPONSE_PLAN = "EVENT_RESPONSE_PLAN"
    EVENT_RESOLUTION = "EVENT_RESOLUTION"
    EVENT_PATTERN = "EVENT_PATTERN"
    # Phase 5.35 Knowledge Intelligence Resource Types
    KNOWLEDGE_PROVENANCE = "KNOWLEDGE_PROVENANCE"
    KNOWLEDGE_RELATIONSHIP = "KNOWLEDGE_RELATIONSHIP"
    KNOWLEDGE_CONTRADICTION = "KNOWLEDGE_CONTRADICTION"
    KNOWLEDGE_RECOMMENDATION = "KNOWLEDGE_RECOMMENDATION"
    KNOWLEDGE_INVESTIGATION = "KNOWLEDGE_INVESTIGATION"
    ORGANIZATIONAL_MEMORY = "ORGANIZATIONAL_MEMORY"
    KNOWLEDGE_LEARNING_RECORD = "KNOWLEDGE_LEARNING_RECORD"
    # Phase 5.37 Platform Resilience Resource Types
    RESILIENCE_SERVICE = "RESILIENCE_SERVICE"
    CAPACITY_PROFILE = "CAPACITY_PROFILE"
    SCALING_PLAN = "SCALING_PLAN"
    FAILOVER_REQUEST = "FAILOVER_REQUEST"
    DISASTER_RECOVERY_PLAN = "DISASTER_RECOVERY_PLAN"
    RECOVERY_PLAN = "RECOVERY_PLAN"
    BACKUP_REFERENCE = "BACKUP_REFERENCE"
    RESTORE_REQUEST = "RESTORE_REQUEST"
    OPERATIONAL_RUNBOOK = "OPERATIONAL_RUNBOOK"
    READINESS_ASSESSMENT = "READINESS_ASSESSMENT"
    RESILIENCE_EXPERIMENT = "RESILIENCE_EXPERIMENT"
    RESILIENCE_SNAPSHOT = "RESILIENCE_SNAPSHOT"
    # Phase 5.38 Control Assurance Resource Types
    CONTROL_ASSURANCE_CONTROL = "CONTROL_ASSURANCE_CONTROL"
    CONTROL_FRAMEWORK = "CONTROL_FRAMEWORK"
    CONTROL_EVALUATION = "CONTROL_EVALUATION"
    CONTROL_VIOLATION = "CONTROL_VIOLATION"
    CONTROL_EVIDENCE = "CONTROL_EVIDENCE"
    CONTROL_EXCEPTION = "CONTROL_EXCEPTION"
    CONTROL_REMEDIATION_PLAN = "CONTROL_REMEDIATION_PLAN"
    CONTROL_VERIFICATION = "CONTROL_VERIFICATION"
    CONTROL_ATTESTATION = "CONTROL_ATTESTATION"
    CONTROL_ASSURANCE_SNAPSHOT = "CONTROL_ASSURANCE_SNAPSHOT"

    # Phase 5.39 Access Intelligence Resource Types
    ACCESS_IDENTITY = "ACCESS_IDENTITY"
    ACCESS_ENTITLEMENT = "ACCESS_ENTITLEMENT"
    ACCESS_RELATIONSHIP = "ACCESS_RELATIONSHIP"
    PRIVILEGED_ACCESS_REQUEST = "PRIVILEGED_ACCESS_REQUEST"
    EMERGENCY_ACCESS_REQUEST = "EMERGENCY_ACCESS_REQUEST"
    ACCESS_CERTIFICATION = "ACCESS_CERTIFICATION"
    ACCESS_ANOMALY = "ACCESS_ANOMALY"
    ACCESS_INVESTIGATION = "ACCESS_INVESTIGATION"
    ACCESS_REMEDIATION = "ACCESS_REMEDIATION"
    ACCESS_EVIDENCE = "ACCESS_EVIDENCE"
    ACCESS_SNAPSHOT = "ACCESS_SNAPSHOT"

    # Phase 5.40 Integration Intelligence Resource Types
    INTEGRATION_ENDPOINT = "INTEGRATION_ENDPOINT"
    INTEGRATION_WORKFLOW = "INTEGRATION_WORKFLOW"
    INTEGRATION_MAPPING = "INTEGRATION_MAPPING"
    INTEGRATION_PLAN = "INTEGRATION_PLAN"
    INTEGRATION_FAILURE = "INTEGRATION_FAILURE"
    INTEGRATION_RECOVERY = "INTEGRATION_RECOVERY"
    INTEGRATION_COMPENSATION = "INTEGRATION_COMPENSATION"
    INTEGRATION_INVESTIGATION = "INTEGRATION_INVESTIGATION"
    INTEGRATION_EVIDENCE = "INTEGRATION_EVIDENCE"
    INTEGRATION_SNAPSHOT = "INTEGRATION_SNAPSHOT"

    # Phase 5.41 Operations Intelligence Resource Types
    OPERATIONAL_SERVICE = "OPERATIONAL_SERVICE"
    OPERATIONAL_INCIDENT = "OPERATIONAL_INCIDENT"
    MAJOR_INCIDENT = "MAJOR_INCIDENT"
    OPERATIONAL_ALERT = "OPERATIONAL_ALERT"
    OPERATIONAL_PROBLEM = "OPERATIONAL_PROBLEM"
    KNOWN_ERROR = "KNOWN_ERROR"
    OPERATIONAL_CHANGE = "OPERATIONAL_CHANGE"
    OPERATIONAL_REMEDIATION = "OPERATIONAL_REMEDIATION"
    OPERATIONAL_INVESTIGATION = "OPERATIONAL_INVESTIGATION"
    OPERATIONAL_EVIDENCE = "OPERATIONAL_EVIDENCE"
    OPERATIONAL_SNAPSHOT = "OPERATIONAL_SNAPSHOT"

    # Phase 5.42 FinOps Intelligence Resource Types
    FINOPS_COST_RECORD = "FINOPS_COST_RECORD"
    FINOPS_USAGE_RECORD = "FINOPS_USAGE_RECORD"
    FINOPS_ALLOCATION = "FINOPS_ALLOCATION"
    FINOPS_BUDGET = "FINOPS_BUDGET"
    FINOPS_FORECAST = "FINOPS_FORECAST"
    FINOPS_ANOMALY = "FINOPS_ANOMALY"
    FINOPS_OPTIMIZATION = "FINOPS_OPTIMIZATION"
    FINOPS_INVESTIGATION = "FINOPS_INVESTIGATION"
    FINOPS_EVIDENCE = "FINOPS_EVIDENCE"
    FINOPS_SNAPSHOT = "FINOPS_SNAPSHOT"

    # Phase 5.43 Data Intelligence Resource Types
    DATASET_REFERENCE = "DATASET_REFERENCE"
    DATA_SOURCE_REFERENCE = "DATA_SOURCE_REFERENCE"
    # DATA_QUALITY_RESULT = "DATA_QUALITY_RESULT" (already defined in Phase 5.25)
    DATA_ANOMALY = "DATA_ANOMALY"
    DATA_DRIFT = "DATA_DRIFT"
    # DATA_LINEAGE = "DATA_LINEAGE" (already defined in Phase 5.12)
    # DATA_SCHEMA = "DATA_SCHEMA" (already defined in Phase 5.12)
    DATA_PIPELINE = "DATA_PIPELINE"
    DATA_INCIDENT = "DATA_INCIDENT"
    DATA_INVESTIGATION = "DATA_INVESTIGATION"
    DATA_REMEDIATION = "DATA_REMEDIATION"
    DATA_EVIDENCE = "DATA_EVIDENCE"
    DATA_INTELLIGENCE_SNAPSHOT = "DATA_INTELLIGENCE_SNAPSHOT"

    # Phase 5.44 Model Intelligence Resource Types
    MODEL_REFERENCE = "MODEL_REFERENCE"
    # MODEL_VERSION = "MODEL_VERSION" (already defined in Phase 5.10)
    MODEL_EVALUATION = "MODEL_EVALUATION"
    MODEL_BENCHMARK = "MODEL_BENCHMARK"
    MODEL_PERFORMANCE = "MODEL_PERFORMANCE"
    MODEL_QUALITY = "MODEL_QUALITY"
    MODEL_HALLUCINATION = "MODEL_HALLUCINATION"
    MODEL_DRIFT = "MODEL_DRIFT"
    MODEL_SAFETY = "MODEL_SAFETY"
    MODEL_SECURITY = "MODEL_SECURITY"
    MODEL_ANOMALY = "MODEL_ANOMALY"
    MODEL_INCIDENT = "MODEL_INCIDENT"
    MODEL_INVESTIGATION = "MODEL_INVESTIGATION"
    MODEL_REMEDIATION = "MODEL_REMEDIATION"
    MODEL_EVIDENCE = "MODEL_EVIDENCE"
    MODEL_ASSURANCE = "MODEL_ASSURANCE"
    MODEL_SNAPSHOT = "MODEL_SNAPSHOT"

    # Phase 5.45 Decision Governance Resource Types
    DECISION_RECORD = "DECISION_RECORD"
    DECISION_PLAN = "DECISION_PLAN"
    # DECISION_RECOMMENDATION = "DECISION_RECOMMENDATION" (already defined in Phase 5.29)
    DECISION_ALTERNATIVE = "DECISION_ALTERNATIVE"
    # DECISION_SCENARIO = "DECISION_SCENARIO" (already defined in Phase 5.29)
    DECISION_SIMULATION = "DECISION_SIMULATION"
    DECISION_CONFLICT = "DECISION_CONFLICT"
    DECISION_INVESTIGATION = "DECISION_INVESTIGATION"
    # DECISION_EVIDENCE = "DECISION_EVIDENCE" (already defined in Phase 5.29)
    DECISION_ASSURANCE = "DECISION_ASSURANCE"
    DECISION_SNAPSHOT = "DECISION_SNAPSHOT"

    # Phase 5.46 Knowledge Assurance Resource Types
    KNOWLEDGE_REFERENCE = "KNOWLEDGE_REFERENCE"
    KNOWLEDGE_CONTEXT = "KNOWLEDGE_CONTEXT"
    KNOWLEDGE_GAP = "KNOWLEDGE_GAP"
    KNOWLEDGE_EVIDENCE = "KNOWLEDGE_EVIDENCE"
    KNOWLEDGE_ASSURANCE = "KNOWLEDGE_ASSURANCE"
    KNOWLEDGE_SNAPSHOT = "KNOWLEDGE_SNAPSHOT"

    # Phase 5.48 Identity Assurance Resource Types
    IDENTITY_REFERENCE = "IDENTITY_REFERENCE"
    IDENTITY_PROFILE = "IDENTITY_PROFILE"
    IDENTITY_TRUST = "IDENTITY_TRUST"
    IDENTITY_PRIVILEGE = "IDENTITY_PRIVILEGE"
    IDENTITY_ENTITLEMENT = "IDENTITY_ENTITLEMENT"
    IDENTITY_ACCESS_PATTERN = "IDENTITY_ACCESS_PATTERN"
    IDENTITY_ANOMALY = "IDENTITY_ANOMALY"
    # ACCESS_REVIEW = "ACCESS_REVIEW" (already defined in Phase 5.15)
    IDENTITY_CERTIFICATION = "IDENTITY_CERTIFICATION"
    IDENTITY_INVESTIGATION = "IDENTITY_INVESTIGATION"
    IDENTITY_EVIDENCE = "IDENTITY_EVIDENCE"
    IDENTITY_ASSURANCE = "IDENTITY_ASSURANCE"
    IDENTITY_SNAPSHOT = "IDENTITY_SNAPSHOT"

    # Phase 5.49 Operations Assurance Resource Types
    OPERATIONAL_SERVICE_HEALTH = "OPERATIONAL_SERVICE_HEALTH"
    OPERATIONAL_DEPENDENCY = "OPERATIONAL_DEPENDENCY"
    OPERATIONAL_EVENT = "OPERATIONAL_EVENT"
    OPERATIONAL_ANOMALY = "OPERATIONAL_ANOMALY"
    OPERATIONAL_ROOT_CAUSE = "OPERATIONAL_ROOT_CAUSE"
    OPERATIONAL_CAPACITY = "OPERATIONAL_CAPACITY"
    OPERATIONAL_FORECAST = "OPERATIONAL_FORECAST"
    OPERATIONAL_RECOMMENDATION = "OPERATIONAL_RECOMMENDATION"
    OPERATIONAL_PLAN = "OPERATIONAL_PLAN"
    OPERATIONAL_ASSURANCE = "OPERATIONAL_ASSURANCE"

    # Phase 5.50 Security Assurance Resource Types
    SECURITY_ASSURANCE_POSTURE = "SECURITY_ASSURANCE_POSTURE"
    SECURITY_THREAT_DETECTION = "SECURITY_THREAT_DETECTION"
    SECURITY_THREAT_CORRELATION = "SECURITY_THREAT_CORRELATION"
    SECURITY_VULNERABILITY_RISK = "SECURITY_VULNERABILITY_RISK"
    SECURITY_ATTACK_SURFACE = "SECURITY_ATTACK_SURFACE"
    SECURITY_SECRETS_INTELLIGENCE = "SECURITY_SECRETS_INTELLIGENCE"
    SECURITY_INCIDENT_INTELLIGENCE = "SECURITY_INCIDENT_INTELLIGENCE"
    SECURITY_ASSURANCE_EVIDENCE = "SECURITY_ASSURANCE_EVIDENCE"
    SECURITY_ASSURANCE_SNAPSHOT = "SECURITY_ASSURANCE_SNAPSHOT"

    # Phase 5.51 Unified Intelligence Resource Types
    UNIFIED_SIGNAL = "UNIFIED_SIGNAL"
    UNIFIED_CONTEXT = "UNIFIED_CONTEXT"
    ENTERPRISE_SITUATION = "ENTERPRISE_SITUATION"
    CORRELATION_GROUP = "CORRELATION_GROUP"
    CAUSAL_HYPOTHESIS = "CAUSAL_HYPOTHESIS"
    RISK_PROPAGATION_GRAPH = "RISK_PROPAGATION_GRAPH"
    UNIFIED_IMPACT = "UNIFIED_IMPACT"
    UNIFIED_RISK = "UNIFIED_RISK"
    UNIFIED_ASSURANCE_POSTURE = "UNIFIED_ASSURANCE_POSTURE"
    UNIFIED_TRUST_ASSESSMENT = "UNIFIED_TRUST_ASSESSMENT"
    UNIFIED_RECOMMENDATION = "UNIFIED_RECOMMENDATION"
    COORDINATION_PLAN = "COORDINATION_PLAN"
    UNIFIED_INVESTIGATION = "UNIFIED_INVESTIGATION"
    UNIFIED_EVIDENCE_RECORD = "UNIFIED_EVIDENCE_RECORD"
    UNIFIED_SNAPSHOT = "UNIFIED_SNAPSHOT"

    # Phase 5.52 Decision Intelligence Resource Types
    DECISION_REPRODUCIBILITY = "DECISION_REPRODUCIBILITY"
    DECISION_UNCERTAINTY = "DECISION_UNCERTAINTY"
    DECISION_SIMULATION_RESULT = "DECISION_SIMULATION_RESULT"

    # Phase 5.53 Autonomous Assurance Resource Types
    AUTONOMOUS_WORKFLOW = "AUTONOMOUS_WORKFLOW"
    AUTONOMOUS_PLAN = "AUTONOMOUS_PLAN"
    WORKFLOW_STEP = "WORKFLOW_STEP"
    WORKFLOW_APPROVAL = "WORKFLOW_APPROVAL"
    WORKFLOW_DELEGATION = "WORKFLOW_DELEGATION"
    WORKFLOW_VERIFICATION = "WORKFLOW_VERIFICATION"
    WORKFLOW_RECOVERY = "WORKFLOW_RECOVERY"
    WORKFLOW_COMPENSATION = "WORKFLOW_COMPENSATION"
    WORKFLOW_EVIDENCE = "WORKFLOW_EVIDENCE"
    AUTONOMOUS_ASSURANCE = "AUTONOMOUS_ASSURANCE"
    AUTONOMOUS_SNAPSHOT = "AUTONOMOUS_SNAPSHOT"

    # Phase 5.54 Continuous Assurance Resource Types
    RUNTIME_OBSERVATION = "RUNTIME_OBSERVATION"
    CONTINUOUS_ASSURANCE = "CONTINUOUS_ASSURANCE"
    ASSURANCE_ASSESSMENT = "ASSURANCE_ASSESSMENT"
    ASSURANCE_DRIFT = "ASSURANCE_DRIFT"
    CONTROL_EFFECTIVENESS = "CONTROL_EFFECTIVENESS"
    CONTINUOUS_VERIFICATION = "CONTINUOUS_VERIFICATION"
    ADAPTIVE_RECOMMENDATION = "ADAPTIVE_RECOMMENDATION"
    ASSURANCE_ESCALATION = "ASSURANCE_ESCALATION"
    CONTINUOUS_EVIDENCE = "CONTINUOUS_EVIDENCE"
    ASSURANCE_SNAPSHOT = "ASSURANCE_SNAPSHOT"
    ASSURANCE_BASELINE = "ASSURANCE_BASELINE"
    ASSURANCE_FEEDBACK = "ASSURANCE_FEEDBACK"

    # Phase 5.55 Reliability Intelligence Resource Types
    RELIABILITY_SERVICE_HEALTH = "RELIABILITY_SERVICE_HEALTH"
    RELIABILITY_ASSESSMENT = "RELIABILITY_ASSESSMENT"
    RELIABILITY_SLO = "RELIABILITY_SLO"
    RELIABILITY_ERROR_BUDGET = "RELIABILITY_ERROR_BUDGET"
    RELIABILITY_FAILURE_EVENT = "RELIABILITY_FAILURE_EVENT"
    RELIABILITY_FAILURE_PREDICTION = "RELIABILITY_FAILURE_PREDICTION"
    RELIABILITY_ANOMALY = "RELIABILITY_ANOMALY"
    RELIABILITY_DEPENDENCY_GRAPH = "RELIABILITY_DEPENDENCY_GRAPH"
    RELIABILITY_FAILURE_PROPAGATION = "RELIABILITY_FAILURE_PROPAGATION"
    RELIABILITY_BLAST_RADIUS = "RELIABILITY_BLAST_RADIUS"
    RELIABILITY_RESILIENCE_ASSESSMENT = "RELIABILITY_RESILIENCE_ASSESSMENT"
    RELIABILITY_DEGRADATION_PLAN = "RELIABILITY_DEGRADATION_PLAN"
    RELIABILITY_RECOVERY_PLAN = "RELIABILITY_RECOVERY_PLAN"
    RELIABILITY_RECOVERY_READINESS = "RELIABILITY_RECOVERY_READINESS"
    RELIABILITY_RECOMMENDATION = "RELIABILITY_RECOMMENDATION"
    RELIABILITY_DELEGATION = "RELIABILITY_DELEGATION"
    RELIABILITY_VERIFICATION = "RELIABILITY_VERIFICATION"
    RELIABILITY_ASSURANCE = "RELIABILITY_ASSURANCE"
    RELIABILITY_EVIDENCE = "RELIABILITY_EVIDENCE"
    RELIABILITY_SNAPSHOT = "RELIABILITY_SNAPSHOT"

    # Phase 5.54 Runtime Intelligence Resource Types
    RUNTIME_SIGNAL = "RUNTIME_SIGNAL"
    RUNTIME_CONTEXT = "RUNTIME_CONTEXT"
    RUNTIME_HEALTH = "RUNTIME_HEALTH"
    RUNTIME_ANOMALY = "RUNTIME_ANOMALY"
    RUNTIME_DRIFT = "RUNTIME_DRIFT"
    RUNTIME_BASELINE = "RUNTIME_BASELINE"
    RUNTIME_DEGRADATION = "RUNTIME_DEGRADATION"
    RUNTIME_CORRELATION = "RUNTIME_CORRELATION"
    RUNTIME_CAUSAL_ANALYSIS = "RUNTIME_CAUSAL_ANALYSIS"
    RUNTIME_RISK_PROPAGATION = "RUNTIME_RISK_PROPAGATION"
    RUNTIME_IMPACT = "RUNTIME_IMPACT"
    RUNTIME_RESILIENCE = "RUNTIME_RESILIENCE"
    RUNTIME_RECOVERY = "RUNTIME_RECOVERY"
    RUNTIME_ADAPTIVE_ASSURANCE = "RUNTIME_ADAPTIVE_ASSURANCE"
    RUNTIME_RECOMMENDATION = "RUNTIME_RECOMMENDATION"
    RUNTIME_EVIDENCE = "RUNTIME_EVIDENCE"
    RUNTIME_SNAPSHOT = "RUNTIME_SNAPSHOT"

    # Phase 5.56 Capacity Intelligence Resource Types
    CAPACITY_RESOURCE = "CAPACITY_RESOURCE"
    CAPACITY_TELEMETRY = "CAPACITY_TELEMETRY"
    CAPACITY_WORKLOAD = "CAPACITY_WORKLOAD"
    CAPACITY_ASSESSMENT_V2 = "CAPACITY_ASSESSMENT_V2"
    CAPACITY_FORECAST = "CAPACITY_FORECAST"
    CAPACITY_DEMAND_PREDICTION = "CAPACITY_DEMAND_PREDICTION"
    CAPACITY_SATURATION = "CAPACITY_SATURATION"
    CAPACITY_BOTTLENECK = "CAPACITY_BOTTLENECK"
    CAPACITY_RESOURCE_EFFICIENCY = "CAPACITY_RESOURCE_EFFICIENCY"
    CAPACITY_OPTIMIZATION = "CAPACITY_OPTIMIZATION"
    CAPACITY_COST_PERFORMANCE = "CAPACITY_COST_PERFORMANCE"
    CAPACITY_TRADEOFF = "CAPACITY_TRADEOFF"
    CAPACITY_PROPAGATION = "CAPACITY_PROPAGATION"
    CAPACITY_RELIABILITY_IMPACT = "CAPACITY_RELIABILITY_IMPACT"
    CAPACITY_SCENARIO = "CAPACITY_SCENARIO"
    CAPACITY_RECOMMENDATION = "CAPACITY_RECOMMENDATION"
    CAPACITY_DELEGATION = "CAPACITY_DELEGATION"
    CAPACITY_ASSURANCE = "CAPACITY_ASSURANCE"
    CAPACITY_EVIDENCE = "CAPACITY_EVIDENCE"
    CAPACITY_SNAPSHOT = "CAPACITY_SNAPSHOT"































class PlatformResource(BaseModel):
    """Universal platform resource entry."""

    resource_id: str
    resource_type: ResourceType
    name: str
    tenant_id: str = "global"
    organization_id: Optional[str] = None
    workspace_id: Optional[str] = None
    owner_id: str = "system"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    status: str = "ACTIVE"
    version: str = "1.0.0"
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ResourceRegistry:
    """Central registry keeping inventory of all assets across all 16 platform subsystems."""

    def __init__(self) -> None:
        self._resources: Dict[str, PlatformResource] = {}
        self._type_index: Dict[ResourceType, List[str]] = {t: [] for t in ResourceType}

    def register_resource(
        self,
        resource_id: str,
        resource_type: ResourceType,
        name: str,
        tenant_id: str = "global",
        organization_id: Optional[str] = None,
        workspace_id: Optional[str] = None,
        owner_id: str = "system",
        status: str = "ACTIVE",
        version: str = "1.0.0",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> PlatformResource:
        """Register or update a managed platform resource."""
        res = PlatformResource(
            resource_id=resource_id,
            resource_type=resource_type,
            name=name,
            tenant_id=tenant_id,
            organization_id=organization_id,
            workspace_id=workspace_id,
            owner_id=owner_id,
            status=status,
            version=version,
            metadata=metadata or {},
        )
        self._resources[resource_id] = res

        if resource_id not in self._type_index[resource_type]:
            self._type_index[resource_type].append(resource_id)

        logger.info(f"[RESOURCE REGISTRY] Registered resource '{name}' (ID: {resource_id}, Type: {resource_type.value})")
        return res

    def unregister_resource(self, resource_id: str) -> bool:
        """Remove a resource from the registry."""
        if resource_id not in self._resources:
            raise ResourceNotFoundException(resource_id)

        res = self._resources[resource_id]
        if resource_id in self._type_index[res.resource_type]:
            self._type_index[res.resource_type].remove(resource_id)
        del self._resources[resource_id]

        logger.info(f"[RESOURCE REGISTRY] Unregistered resource '{resource_id}'")
        return True

    def get_resource(self, resource_id: str) -> PlatformResource:
        """Get resource by ID."""
        res = self._resources.get(resource_id)
        if not res:
            raise ResourceNotFoundException(resource_id)
        return res

    def list_resources(
        self,
        tenant_id: Optional[str] = None,
        organization_id: Optional[str] = None,
        workspace_id: Optional[str] = None,
        resource_type: Optional[ResourceType] = None,
    ) -> List[PlatformResource]:
        """List resources matching scope filters."""
        res_list = list(self._resources.values())
        if tenant_id:
            res_list = [r for r in res_list if r.tenant_id == tenant_id]
        if organization_id:
            res_list = [r for r in res_list if r.organization_id == organization_id]
        if workspace_id:
            res_list = [r for r in res_list if r.workspace_id == workspace_id]
        if resource_type:
            res_list = [r for r in res_list if r.resource_type == resource_type]
        return res_list

    def search_resources(self, query: str, tenant_id: Optional[str] = None) -> List[PlatformResource]:
        """Search resources by name or ID snippet."""
        q_norm = query.lower()
        res_list = self.list_resources(tenant_id=tenant_id)
        return [r for r in res_list if q_norm in r.name.lower() or q_norm in r.resource_id.lower()]

    def get_resource_owner(self, resource_id: str) -> str:
        """Get owner ID of resource."""
        return self.get_resource(resource_id).owner_id

    def get_resource_usage(self, resource_id: str) -> Dict[str, Any]:
        """Get resource usage metadata."""
        res = self.get_resource(resource_id)
        return {
            "resource_id": resource_id,
            "status": res.status,
            "version": res.version,
            "usage_count": res.metadata.get("usage_count", 0),
        }
