"""initial_schema

Revision ID: 42877874b3e7
Revises: 
Create Date: 2026-09-15 08:59:47.603126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42877874b3e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assets',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_ai_assets_asset_type'), 'ai_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_ai_assets_name'), 'ai_assets', ['name'], unique=False)
    op.create_index(op.f('ix_ai_assets_status'), 'ai_assets', ['status'], unique=False)
    op.create_index(op.f('ix_ai_assets_tenant_id'), 'ai_assets', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_category'), 'audit_events', ['category'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_events_severity'), 'audit_events', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_events_source'), 'audit_events', ['source'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('hard_limit', sa.Float(), nullable=False),
    sa.Column('critical_threshold', sa.Float(), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_organization_id'), 'budgets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_budgets_workspace_id'), 'budgets', ['workspace_id'], unique=False)
    op.create_table('dead_letter_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('endpoint_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('replay_count', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_events_delivery_id'), 'dead_letter_events', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_events_endpoint_id'), 'dead_letter_events', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_events_event_id'), 'dead_letter_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_events_failed_at'), 'dead_letter_events', ['failed_at'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'SENT', 'PAID', 'ARCHIVED', name='invoicestatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_organization_id'), 'knowledge_bases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_workspace_id'), 'knowledge_bases', ['workspace_id'], unique=False)
    op.create_table('model_registrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registrations_provider'), 'model_registrations', ['provider'], unique=False)
    op.create_index(op.f('ix_model_registrations_status'), 'model_registrations', ['status'], unique=False)
    op.create_table('observability_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('condition_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_alerts_alert_id'), 'observability_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_observability_alerts_condition_type'), 'observability_alerts', ['condition_type'], unique=False)
    op.create_index(op.f('ix_observability_alerts_created_at'), 'observability_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_alerts_level'), 'observability_alerts', ['level'], unique=False)
    op.create_index(op.f('ix_observability_alerts_status'), 'observability_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_observability_alerts_tenant_id'), 'observability_alerts', ['tenant_id'], unique=False)
    op.create_table('observability_anomaly_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_id', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_anomaly_events_anomaly_id'), 'observability_anomaly_events', ['anomaly_id'], unique=True)
    op.create_index(op.f('ix_observability_anomaly_events_anomaly_type'), 'observability_anomaly_events', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_observability_anomaly_events_component'), 'observability_anomaly_events', ['component'], unique=False)
    op.create_index(op.f('ix_observability_anomaly_events_created_at'), 'observability_anomaly_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_anomaly_events_severity'), 'observability_anomaly_events', ['severity'], unique=False)
    op.create_table('observability_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('task_completion_rate', sa.Float(), nullable=True),
    sa.Column('planning_confidence', sa.Float(), nullable=True),
    sa.Column('critique_score', sa.Float(), nullable=True),
    sa.Column('user_feedback_score', sa.Float(), nullable=True),
    sa.Column('hallucination_signal', sa.Float(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_evaluations_agent_id'), 'observability_evaluations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_observability_evaluations_created_at'), 'observability_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_evaluations_execution_id'), 'observability_evaluations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_observability_evaluations_model_id'), 'observability_evaluations', ['model_id'], unique=False)
    op.create_index(op.f('ix_observability_evaluations_workflow_id'), 'observability_evaluations', ['workflow_id'], unique=False)
    op.create_table('observability_execution_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_execution_events_event_type'), 'observability_execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_observability_execution_events_execution_id'), 'observability_execution_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_observability_execution_events_span_id'), 'observability_execution_events', ['span_id'], unique=False)
    op.create_index(op.f('ix_observability_execution_events_tenant_id'), 'observability_execution_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_observability_execution_events_trace_id'), 'observability_execution_events', ['trace_id'], unique=False)
    op.create_table('observability_slo_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slo_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_component', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=True),
    sa.Column('window_seconds', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_slo_definitions_slo_id'), 'observability_slo_definitions', ['slo_id'], unique=True)
    op.create_index(op.f('ix_observability_slo_definitions_target_component'), 'observability_slo_definitions', ['target_component'], unique=False)
    op.create_index(op.f('ix_observability_slo_definitions_tenant_id'), 'observability_slo_definitions', ['tenant_id'], unique=False)
    op.create_table('observability_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('original_output', sa.JSON(), nullable=True),
    sa.Column('original_status', sa.String(length=32), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_snapshots_execution_id'), 'observability_snapshots', ['execution_id'], unique=True)
    op.create_index(op.f('ix_observability_snapshots_snapshot_id'), 'observability_snapshots', ['snapshot_id'], unique=True)
    op.create_index(op.f('ix_observability_snapshots_tenant_id'), 'observability_snapshots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_observability_snapshots_trace_id'), 'observability_snapshots', ['trace_id'], unique=False)
    op.create_table('observability_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_traces_created_at'), 'observability_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_traces_execution_id'), 'observability_traces', ['execution_id'], unique=False)
    op.create_index(op.f('ix_observability_traces_organization_id'), 'observability_traces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_observability_traces_status'), 'observability_traces', ['status'], unique=False)
    op.create_index(op.f('ix_observability_traces_tenant_id'), 'observability_traces', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_observability_traces_trace_id'), 'observability_traces', ['trace_id'], unique=True)
    op.create_index(op.f('ix_observability_traces_workspace_id'), 'observability_traces', ['workspace_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_by', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('pricing_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_cost_per_1k_tokens', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1k_tokens', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_model'), 'pricing_rules', ['model'], unique=False)
    op.create_index(op.f('ix_pricing_rules_provider'), 'pricing_rules', ['provider'], unique=False)
    op.create_table('quota_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('parent_policy_id', sa.String(), nullable=True),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('requests_per_hour', sa.Integer(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('tokens_per_day', sa.Integer(), nullable=True),
    sa.Column('tokens_per_month', sa.Integer(), nullable=True),
    sa.Column('concurrent_requests', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_policy_id'], ['quota_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_policies_api_key_id'), 'quota_policies', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_quota_policies_organization_id'), 'quota_policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_quota_policies_user_id'), 'quota_policies', ['user_id'], unique=False)
    op.create_index(op.f('ix_quota_policies_workspace_id'), 'quota_policies', ['workspace_id'], unique=False)
    op.create_table('quota_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('window_id', sa.String(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_windows_scope_id'), 'quota_windows', ['scope_id'], unique=False)
    op.create_index(op.f('ix_quota_windows_window_id'), 'quota_windows', ['window_id'], unique=False)
    op.create_table('rate_limit_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_policies_api_key_id'), 'rate_limit_policies', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_organization_id'), 'rate_limit_policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_workspace_id'), 'rate_limit_policies', ['workspace_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_jobs_created_by'), 'report_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_report_jobs_status'), 'report_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_report_jobs_type'), 'report_jobs', ['type'], unique=False)
    op.create_table('retrieval_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_sessions_workspace_id'), 'retrieval_sessions', ['workspace_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('quota_policy_template_id', sa.String(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_workspaces', sa.Integer(), nullable=True),
    sa.Column('priority_support', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('request_tokens', sa.Integer(), nullable=False),
    sa.Column('response_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_model'), 'usage_records', ['model'], unique=False)
    op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_records_provider'), 'usage_records', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_records_workspace_id'), 'usage_records', ['workspace_id'], unique=False)
    op.create_table('usage_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_snapshots_date'), 'usage_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_usage_snapshots_organization_id'), 'usage_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_snapshots_workspace_id'), 'usage_snapshots', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('default_organization_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('secondary_secret', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_enabled'), 'webhook_endpoints', ['enabled'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_organization_id'), 'webhook_endpoints', ['organization_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_correlation_id'), 'webhook_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_organization_id'), 'webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_timestamp'), 'webhook_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_webhook_events_workspace_id'), 'webhook_events', ['workspace_id'], unique=False)
    op.create_table('ai_asset_versions',
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('configuration_json', sa.Text(), nullable=True),
    sa.Column('configuration_hash', sa.String(), nullable=True),
    sa.Column('dependencies_json', sa.Text(), nullable=True),
    sa.Column('parent_version', sa.String(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ai_assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('idx_asset_version_num', 'ai_asset_versions', ['asset_id', 'version_number'], unique=True)
    op.create_index(op.f('ix_ai_asset_versions_asset_id'), 'ai_asset_versions', ['asset_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threshold', sa.String(), nullable=False),
    sa.Column('current_usage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_alerts_budget_id'), 'budget_alerts', ['budget_id'], unique=False)
    op.create_table('index_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_base_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_jobs_knowledge_base_id'), 'index_jobs', ['knowledge_base_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_base_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content_uri', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_by', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('memberships',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('observability_slo_violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slo_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['slo_id'], ['observability_slo_definitions.slo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_slo_violations_created_at'), 'observability_slo_violations', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_slo_violations_slo_id'), 'observability_slo_violations', ['slo_id'], unique=False)
    op.create_table('observability_spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['observability_traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_spans_component'), 'observability_spans', ['component'], unique=False)
    op.create_index(op.f('ix_observability_spans_name'), 'observability_spans', ['name'], unique=False)
    op.create_index(op.f('ix_observability_spans_parent_span_id'), 'observability_spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_observability_spans_span_id'), 'observability_spans', ['span_id'], unique=True)
    op.create_index(op.f('ix_observability_spans_status'), 'observability_spans', ['status'], unique=False)
    op.create_index(op.f('ix_observability_spans_trace_id'), 'observability_spans', ['trace_id'], unique=False)
    op.create_table('organization_settings',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=True)
    op.create_table('payment_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_history_invoice_id'), 'payment_history', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_history_organization_id'), 'payment_history', ['organization_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('endpoint_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('is_replay', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_table('api_key_usages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_usages_api_key_id'), 'api_key_usages', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_usages_timestamp'), 'api_key_usages', ['timestamp'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('section_heading', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_hash', sa.String(), nullable=True),
    sa.Column('parent_chunk', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('citations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_citations_session_id'), 'citations', ['session_id'], unique=False)
    op.create_table('embedding_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_records_chunk_id'), 'embedding_records', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_records_chunk_id'), table_name='embedding_records')
    op.drop_table('embedding_records')
    op.drop_index(op.f('ix_citations_session_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_api_key_usages_timestamp'), table_name='api_key_usages')
    op.drop_index(op.f('ix_api_key_usages_api_key_id'), table_name='api_key_usages')
    op.drop_table('api_key_usages')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_payment_history_organization_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_invoice_id'), table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    op.drop_table('organization_settings')
    op.drop_index(op.f('ix_observability_spans_trace_id'), table_name='observability_spans')
    op.drop_index(op.f('ix_observability_spans_status'), table_name='observability_spans')
    op.drop_index(op.f('ix_observability_spans_span_id'), table_name='observability_spans')
    op.drop_index(op.f('ix_observability_spans_parent_span_id'), table_name='observability_spans')
    op.drop_index(op.f('ix_observability_spans_name'), table_name='observability_spans')
    op.drop_index(op.f('ix_observability_spans_component'), table_name='observability_spans')
    op.drop_table('observability_spans')
    op.drop_index(op.f('ix_observability_slo_violations_slo_id'), table_name='observability_slo_violations')
    op.drop_index(op.f('ix_observability_slo_violations_created_at'), table_name='observability_slo_violations')
    op.drop_table('observability_slo_violations')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_index_jobs_knowledge_base_id'), table_name='index_jobs')
    op.drop_table('index_jobs')
    op.drop_index(op.f('ix_budget_alerts_budget_id'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_asset_versions_asset_id'), table_name='ai_asset_versions')
    op.drop_index('idx_asset_version_num', table_name='ai_asset_versions')
    op.drop_table('ai_asset_versions')
    op.drop_index(op.f('ix_webhook_events_workspace_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_timestamp'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_organization_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_correlation_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_webhook_endpoints_organization_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_enabled'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_snapshots_workspace_id'), table_name='usage_snapshots')
    op.drop_index(op.f('ix_usage_snapshots_organization_id'), table_name='usage_snapshots')
    op.drop_index(op.f('ix_usage_snapshots_date'), table_name='usage_snapshots')
    op.drop_table('usage_snapshots')
    op.drop_index(op.f('ix_usage_records_workspace_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_provider'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_model'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_retrieval_sessions_workspace_id'), table_name='retrieval_sessions')
    op.drop_table('retrieval_sessions')
    op.drop_index(op.f('ix_report_jobs_type'), table_name='report_jobs')
    op.drop_index(op.f('ix_report_jobs_status'), table_name='report_jobs')
    op.drop_index(op.f('ix_report_jobs_created_by'), table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_rate_limit_policies_workspace_id'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_organization_id'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_api_key_id'), table_name='rate_limit_policies')
    op.drop_table('rate_limit_policies')
    op.drop_index(op.f('ix_quota_windows_window_id'), table_name='quota_windows')
    op.drop_index(op.f('ix_quota_windows_scope_id'), table_name='quota_windows')
    op.drop_table('quota_windows')
    op.drop_index(op.f('ix_quota_policies_workspace_id'), table_name='quota_policies')
    op.drop_index(op.f('ix_quota_policies_user_id'), table_name='quota_policies')
    op.drop_index(op.f('ix_quota_policies_organization_id'), table_name='quota_policies')
    op.drop_index(op.f('ix_quota_policies_api_key_id'), table_name='quota_policies')
    op.drop_table('quota_policies')
    op.drop_index(op.f('ix_pricing_rules_provider'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_model'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_observability_traces_workspace_id'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_trace_id'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_tenant_id'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_status'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_organization_id'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_execution_id'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_created_at'), table_name='observability_traces')
    op.drop_table('observability_traces')
    op.drop_index(op.f('ix_observability_snapshots_trace_id'), table_name='observability_snapshots')
    op.drop_index(op.f('ix_observability_snapshots_tenant_id'), table_name='observability_snapshots')
    op.drop_index(op.f('ix_observability_snapshots_snapshot_id'), table_name='observability_snapshots')
    op.drop_index(op.f('ix_observability_snapshots_execution_id'), table_name='observability_snapshots')
    op.drop_table('observability_snapshots')
    op.drop_index(op.f('ix_observability_slo_definitions_tenant_id'), table_name='observability_slo_definitions')
    op.drop_index(op.f('ix_observability_slo_definitions_target_component'), table_name='observability_slo_definitions')
    op.drop_index(op.f('ix_observability_slo_definitions_slo_id'), table_name='observability_slo_definitions')
    op.drop_table('observability_slo_definitions')
    op.drop_index(op.f('ix_observability_execution_events_trace_id'), table_name='observability_execution_events')
    op.drop_index(op.f('ix_observability_execution_events_tenant_id'), table_name='observability_execution_events')
    op.drop_index(op.f('ix_observability_execution_events_span_id'), table_name='observability_execution_events')
    op.drop_index(op.f('ix_observability_execution_events_execution_id'), table_name='observability_execution_events')
    op.drop_index(op.f('ix_observability_execution_events_event_type'), table_name='observability_execution_events')
    op.drop_table('observability_execution_events')
    op.drop_index(op.f('ix_observability_evaluations_workflow_id'), table_name='observability_evaluations')
    op.drop_index(op.f('ix_observability_evaluations_model_id'), table_name='observability_evaluations')
    op.drop_index(op.f('ix_observability_evaluations_execution_id'), table_name='observability_evaluations')
    op.drop_index(op.f('ix_observability_evaluations_created_at'), table_name='observability_evaluations')
    op.drop_index(op.f('ix_observability_evaluations_agent_id'), table_name='observability_evaluations')
    op.drop_table('observability_evaluations')
    op.drop_index(op.f('ix_observability_anomaly_events_severity'), table_name='observability_anomaly_events')
    op.drop_index(op.f('ix_observability_anomaly_events_created_at'), table_name='observability_anomaly_events')
    op.drop_index(op.f('ix_observability_anomaly_events_component'), table_name='observability_anomaly_events')
    op.drop_index(op.f('ix_observability_anomaly_events_anomaly_type'), table_name='observability_anomaly_events')
    op.drop_index(op.f('ix_observability_anomaly_events_anomaly_id'), table_name='observability_anomaly_events')
    op.drop_table('observability_anomaly_events')
    op.drop_index(op.f('ix_observability_alerts_tenant_id'), table_name='observability_alerts')
    op.drop_index(op.f('ix_observability_alerts_status'), table_name='observability_alerts')
    op.drop_index(op.f('ix_observability_alerts_level'), table_name='observability_alerts')
    op.drop_index(op.f('ix_observability_alerts_created_at'), table_name='observability_alerts')
    op.drop_index(op.f('ix_observability_alerts_condition_type'), table_name='observability_alerts')
    op.drop_index(op.f('ix_observability_alerts_alert_id'), table_name='observability_alerts')
    op.drop_table('observability_alerts')
    op.drop_index(op.f('ix_model_registrations_status'), table_name='model_registrations')
    op.drop_index(op.f('ix_model_registrations_provider'), table_name='model_registrations')
    op.drop_table('model_registrations')
    op.drop_index(op.f('ix_knowledge_bases_workspace_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_organization_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_dead_letter_events_failed_at'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_event_id'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_endpoint_id'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_delivery_id'), table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    op.drop_index(op.f('ix_budgets_workspace_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_organization_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_source'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_severity'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_category'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_assets_tenant_id'), table_name='ai_assets')
    op.drop_index(op.f('ix_ai_assets_status'), table_name='ai_assets')
    op.drop_index(op.f('ix_ai_assets_name'), table_name='ai_assets')
    op.drop_index(op.f('ix_ai_assets_asset_type'), table_name='ai_assets')
    op.drop_table('ai_assets')
    # ### end Alembic commands ###
