"""
Phase 5.70 - Reliability Models Module.

Defines canonical enums and data models for Platform Reliability Engineering, Chaos Engineering, and Disaster Recovery.
"""

from enum import Enum


class ReliabilityStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    AT_RISK = "AT_RISK"
    FAILING = "FAILING"
    RECOVERING = "RECOVERING"
    RECOVERED = "RECOVERED"
    CRITICAL = "CRITICAL"
    BLOCKED = "BLOCKED"
    NOT_EXECUTED = "NOT_EXECUTED"


class FailureSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecoveryStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    MANUAL_INTERVENTION_REQUIRED = "MANUAL_INTERVENTION_REQUIRED"
    NOT_EXECUTED = "NOT_EXECUTED"


class ChaosExecutionMode(str, Enum):
    DRY_RUN = "DRY_RUN"
    SIMULATION = "SIMULATION"
    CONTAINER = "CONTAINER"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"


class ChaosFailureType(str, Enum):
    APPLICATION_CRASH = "APPLICATION_CRASH"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    DATABASE_LATENCY = "DATABASE_LATENCY"
    CACHE_UNAVAILABLE = "CACHE_UNAVAILABLE"
    CACHE_LATENCY = "CACHE_LATENCY"
    NETWORK_LATENCY = "NETWORK_LATENCY"
    NETWORK_PARTITION = "NETWORK_PARTITION"
    DEPENDENCY_FAILURE = "DEPENDENCY_FAILURE"
    CONTAINER_RESTART = "CONTAINER_RESTART"
    CONTAINER_UNAVAILABLE = "CONTAINER_UNAVAILABLE"
    RESOURCE_EXHAUSTION = "RESOURCE_EXHAUSTION"
    CPU_PRESSURE = "CPU_PRESSURE"
    MEMORY_PRESSURE = "MEMORY_PRESSURE"
    CONNECTION_POOL_EXHAUSTION = "CONNECTION_POOL_EXHAUSTION"
    TIMEOUT_FAILURE = "TIMEOUT_FAILURE"
    SECURITY_DEPENDENCY_FAILURE = "SECURITY_DEPENDENCY_FAILURE"
