"""
Unified Recommendation Engine for Phase 5.51 Enterprise AI Unified Intelligence.

Generates cross-domain unified recommendations prioritizing remediation actions, risk reduction,
and operational optimization with tenant isolation.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
import uuid

from app.unified_intelligence.exceptions import (
    CrossTenantUnifiedIntelligenceException,
    InvalidUnifiedIntelligenceInputException
)
from app.unified_intelligence.domains import IntelligenceDomain
from app.unified_intelligence.situation_awareness import EnterpriseSituation


class UnifiedRecommendation:
    """
    Cross-domain recommendation generated by Unified Intelligence.
    """
    def __init__(
        self,
        recommendation_id: str,
        tenant_id: str,
        situation_id: Optional[str],
        title: str,
        description: str,
        target_domains: List[IntelligenceDomain],
        action_type: str,  # REMEDIATION, ISOLATION, CONFIGURATION, AUDIT, THROTTLING
        priority: str,     # CRITICAL, HIGH, MEDIUM, LOW
        risk_reduction_score: float,
        requires_human_approval: bool,
        confidence_score: float,
        evidence_ids: List[str],
        created_at: Optional[datetime] = None
    ):
        self.recommendation_id = recommendation_id
        self.tenant_id = tenant_id
        self.situation_id = situation_id
        self.title = title
        self.description = description
        self.target_domains = target_domains
        self.action_type = action_type
        self.priority = priority
        self.risk_reduction_score = min(max(risk_reduction_score, 0.0), 1.0)
        self.requires_human_approval = requires_human_approval
        self.confidence_score = min(max(confidence_score, 0.0), 1.0)
        self.evidence_ids = evidence_ids
        self.created_at = created_at or datetime.utcnow()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "recommendation_id": self.recommendation_id,
            "tenant_id": self.tenant_id,
            "situation_id": self.situation_id,
            "title": self.title,
            "description": self.description,
            "target_domains": [d.value for d in self.target_domains],
            "action_type": self.action_type,
            "priority": self.priority,
            "risk_reduction_score": round(self.risk_reduction_score, 4),
            "requires_human_approval": self.requires_human_approval,
            "confidence_score": round(self.confidence_score, 4),
            "evidence_ids": self.evidence_ids,
            "created_at": self.created_at.isoformat()
        }


class UnifiedRecommendationEngine:
    """
    Engine to compose and prioritize recommendations across multiple domains.
    """
    def __init__(self):
        pass

    def generate_recommendations_for_situation(
        self,
        tenant_id: str,
        situation: EnterpriseSituation
    ) -> List[UnifiedRecommendation]:
        if not tenant_id:
            raise InvalidUnifiedIntelligenceInputException("tenant_id is required")
        if situation.tenant_id != tenant_id:
            raise CrossTenantUnifiedIntelligenceException(
                f"Tenant mismatch in recommendation generation: expected {tenant_id}, got {situation.tenant_id}"
            )

        recs: List[UnifiedRecommendation] = []
        rec_id_base = uuid.uuid4().hex[:8]

        # Recommendation 1: Cross-Domain Stabilization
        recs.append(
            UnifiedRecommendation(
                recommendation_id=f"rec-{rec_id_base}-1",
                tenant_id=tenant_id,
                situation_id=situation.situation_id,
                title=f"Cross-Domain Isolation for Situation '{situation.title}'",
                description=f"Temporarily quarantine affected entities across participating domains: {[d.value for d in situation.participating_domains]}.",
                target_domains=situation.participating_domains,
                action_type="ISOLATION",
                priority="HIGH" if situation.severity.value in ["HIGH", "CRITICAL"] else "MEDIUM",
                risk_reduction_score=0.75,
                requires_human_approval=True,
                confidence_score=situation.confidence_score * 0.9,
                evidence_ids=situation.evidence_references
            )
        )

        # Recommendation 2: Root Cause Audit
        recs.append(
            UnifiedRecommendation(
                recommendation_id=f"rec-{rec_id_base}-2",
                tenant_id=tenant_id,
                situation_id=situation.situation_id,
                title=f"Trigger Targeted Root Cause Audit across {len(situation.affected_entities)} Entities",
                description=f"Perform deep analysis on entities {situation.affected_entities[:3]} to confirm cross-domain causality.",
                target_domains=situation.participating_domains,
                action_type="AUDIT",
                priority="MEDIUM",
                risk_reduction_score=0.45,
                requires_human_approval=False,
                confidence_score=situation.confidence_score,
                evidence_ids=situation.evidence_references
            )
        )

        return recs
