"""Enterprise AI Application Platform, Runtime & Experience Layer (Phase 5.22)."""

from app.application_platform.exceptions import (
    ApplicationPlatformException,
    ApplicationNotFoundException,
    ApplicationVersionNotFoundException,
    ImmutableVersionException,
    InvalidLifecycleTransitionException,
    ConsentDeniedException,
    ExecutionCancelledException,
    DeploymentFailedException,
    GovernanceBlockedException,
)
from app.application_platform.repositories import (
    ApplicationRepository,
    InMemoryApplicationRepository,
    SQLAlchemyApplicationRepository,
)
from app.application_platform.application import (
    Application,
    ApplicationVersion,
    ApplicationConfiguration,
    ApplicationType,
    ApplicationStatus,
    ApplicationLifecycle,
    ApplicationRegistry,
)
from app.application_platform.composition import (
    ApplicationComposition,
    ApplicationComponent,
    ComponentBinding,
    ComponentType,
    ApplicationCompositionManager,
)
from app.application_platform.deployment import (
    ApplicationDeployment,
    DeploymentStrategy,
    DeploymentStatus,
    RollbackPolicy,
    DeploymentManager,
)
from app.application_platform.runtime import (
    ApplicationRuntime,
    ApplicationExecution,
    ExecutionContext,
    RuntimeState,
    ApplicationRuntimeManager,
)
from app.application_platform.configuration import (
    ApplicationEnvironment,
    EnvironmentConfiguration,
    ConfigurationVersion,
    ConfigurationManager,
)
from app.application_platform.features import (
    FeatureFlag,
    FeatureVariant,
    FeatureTargetingRule,
    FeatureExperiment,
    FeatureState,
    ExperimentState,
    FeatureManager,
)
from app.application_platform.personalization import (
    PersonalizationConsent,
    ConsentScope,
    ConsentStatus,
    PersonalizationProfile,
    ExperienceContext,
    PersonalizationEngine,
)
from app.application_platform.interactions import (
    Interaction,
    Conversation,
    ConversationState,
    InteractionType,
    InteractionManager,
)
from app.application_platform.human_experience import (
    ExperienceAction,
    HumanEscalation,
    EscalationPolicy,
    EscalationReason,
    HumanExperienceManager,
)
from app.application_platform.governance import (
    ApplicationGovernanceEngine,
    ApplicationPolicyDecision,
    OutputPolicyEvaluator,
    OutputSafetyDecision,
    ResponseTransformation,
    ApplicationRiskAssessment,
)
from app.application_platform.analytics import (
    ApplicationAnalyticsEngine,
    ApplicationMetric,
    ExperienceMetric,
    UsageInsight,
    ApplicationReport,
)
from app.application_platform.feedback import (
    ApplicationFeedback,
    FeedbackType,
    FeedbackSignal,
    ImprovementRecommendation,
    FeedbackManager,
)
from app.application_platform.resilience import (
    ApplicationResilienceManager,
    RuntimeFallback,
    DegradationStrategy,
)
from app.application_platform.observability import (
    ApplicationMetricsCollector,
    ApplicationTelemetrySpan,
)
from app.application_platform.billing import (
    ApplicationExecutionCostEvent,
    ApplicationBillingTracker,
)
from app.application_platform.manager import ApplicationPlatformManager

__all__ = [
    "ApplicationPlatformException",
    "ApplicationNotFoundException",
    "ApplicationVersionNotFoundException",
    "ImmutableVersionException",
    "InvalidLifecycleTransitionException",
    "ConsentDeniedException",
    "ExecutionCancelledException",
    "DeploymentFailedException",
    "GovernanceBlockedException",
    "ApplicationRepository",
    "InMemoryApplicationRepository",
    "SQLAlchemyApplicationRepository",
    "Application",
    "ApplicationVersion",
    "ApplicationConfiguration",
    "ApplicationType",
    "ApplicationStatus",
    "ApplicationLifecycle",
    "ApplicationRegistry",
    "ApplicationComposition",
    "ApplicationComponent",
    "ComponentBinding",
    "ComponentType",
    "ApplicationCompositionManager",
    "ApplicationDeployment",
    "DeploymentStrategy",
    "DeploymentStatus",
    "RollbackPolicy",
    "DeploymentManager",
    "ApplicationRuntime",
    "ApplicationExecution",
    "ExecutionContext",
    "RuntimeState",
    "ApplicationRuntimeManager",
    "ApplicationEnvironment",
    "EnvironmentConfiguration",
    "ConfigurationVersion",
    "ConfigurationManager",
    "FeatureFlag",
    "FeatureVariant",
    "FeatureTargetingRule",
    "FeatureExperiment",
    "FeatureState",
    "ExperimentState",
    "FeatureManager",
    "PersonalizationConsent",
    "ConsentScope",
    "ConsentStatus",
    "PersonalizationProfile",
    "ExperienceContext",
    "PersonalizationEngine",
    "Interaction",
    "Conversation",
    "ConversationState",
    "InteractionType",
    "InteractionManager",
    "ExperienceAction",
    "HumanEscalation",
    "EscalationPolicy",
    "EscalationReason",
    "HumanExperienceManager",
    "ApplicationGovernanceEngine",
    "ApplicationPolicyDecision",
    "OutputPolicyEvaluator",
    "OutputSafetyDecision",
    "ResponseTransformation",
    "ApplicationRiskAssessment",
    "ApplicationAnalyticsEngine",
    "ApplicationMetric",
    "ExperienceMetric",
    "UsageInsight",
    "ApplicationReport",
    "ApplicationFeedback",
    "FeedbackType",
    "FeedbackSignal",
    "ImprovementRecommendation",
    "FeedbackManager",
    "ApplicationResilienceManager",
    "RuntimeFallback",
    "DegradationStrategy",
    "ApplicationMetricsCollector",
    "ApplicationTelemetrySpan",
    "ApplicationExecutionCostEvent",
    "ApplicationBillingTracker",
    "ApplicationPlatformManager",
]
