{{- $enabled := false -}}
{{- $minAvail := 2 -}}
{{- if .Values.podDisruptionBudget -}}
  {{- $enabled = .Values.podDisruptionBudget.enabled -}}
  {{- $minAvail = default 2 .Values.podDisruptionBudget.minAvailable -}}
{{- else if .Values.pdb -}}
  {{- $enabled = .Values.pdb.enabled -}}
  {{- $minAvail = default 2 .Values.pdb.minAvailable -}}
{{- end -}}
{{- if $enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "llm-engine.fullname" . }}-gateway
spec:
  minAvailable: {{ $minAvail }}
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
{{- end }}
