{{- if and .Values.observability .Values.observability.podMonitor .Values.observability.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "llm-engine.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
