{{- if and .Values.persistence .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llm-engine.fullname" . }}-storage
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistence.size }}
{{- end }}
