{{- if and .Values.scheduler .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-engine.fullname" . }}-scheduler
  labels:
    {{- include "llm-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: {{ default 2 (and .Values.scheduler .Values.scheduler.replicaCount) }}
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
    spec:
      serviceAccountName: {{ if and .Values.serviceAccount .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ include "llm-engine.fullname" . }}{{ end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler
          image: "{{ if .Values.image }}{{ default "llm-inference-engine" .Values.image.repository }}:{{ default "1.0.0" .Values.image.tag }}{{ else }}llm-inference-engine:1.0.0{{ end }}"
          command: ["python", "-m", "app.services.request_scheduler"]
          {{- if .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- if and .Values.scheduler .Values.scheduler.resources }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          {{- else if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
{{- end }}
