apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-engine.fullname" . }}-gateway
  labels:
    {{- include "llm-engine.labels" . | nindent 4 }}
spec:
  type: {{ if and .Values.service .Values.service.type }}{{ .Values.service.type }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ if and .Values.service .Values.service.port }}{{ .Values.service.port }}{{ else }}8000{{ end }}
      targetPort: {{ if and .Values.service .Values.service.targetPort }}{{ .Values.service.targetPort }}{{ else }}8000{{ end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: gateway
