{{- if and .Values.observability .Values.observability.serviceMonitor .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-engine.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
